title: Haveno Aloha
description: The flagship instance of Haveno, a decentralized exchange platform.
baseurl: ""
url: "https://www.haveno-aloha.com" # Your GitHub username
markdown: kramdown
theme: minima
permalink: pretty